export const globalCountries = [
  { value: "afghanistan", name: "Afghanistan" },
  { value: "albania", name: "Albania" },
  { value: "algeria", name: "Algeria" },
  { value: "andorra", name: "Andorra" },
  { value: "angola", name: "Angola" },
  { value: "antigua_and_barbuda", name: "Antigua and Barbuda" },
  { value: "argentina", name: "Argentina" },
  { value: "armenia", name: "Armenia" },
  { value: "australia", name: "Australia" },
  { value: "austria", name: "Austria" },
  { value: "azerbaijan", name: "Azerbaijan" },
  { value: "bahamas", name: "Bahamas" },
  { value: "bahrain", name: "Bahrain" },
  { value: "bangladesh", name: "Bangladesh" },
  { value: "barbados", name: "Barbados" },
  { value: "belarus", name: "Belarus" },
  { value: "belgium", name: "Belgium" },
  { value: "belize", name: "Belize" },
  { value: "benin", name: "Benin" },
  { value: "bhutan", name: "Bhutan" },
  { value: "bolivia", name: "Bolivia" },
  { value: "bosnia_and_herzegovina", name: "Bosnia and Herzegovina" },
  { value: "botswana", name: "Botswana" },
  { value: "brazil", name: "Brazil" },
  { value: "brunei", name: "Brunei" },
  { value: "bulgaria", name: "Bulgaria" },
  { value: "burkina_faso", name: "Burkina Faso" },
  { value: "burundi", name: "Burundi" },
  { value: "cote_divoire", name: "Côte d'Ivoire" },
  { value: "cabo_verde", name: "Cabo Verde" },
  { value: "cambodia", name: "Cambodia" },
  { value: "cameroon", name: "Cameroon" },
  { value: "canada", name: "Canada" },
  { value: "central_african_republic", name: "Central African Republic" },
  { value: "chad", name: "Chad" },
  { value: "chile", name: "Chile" },
  { value: "china", name: "China" },
  { value: "colombia", name: "Colombia" },
  { value: "comoros", name: "Comoros" },
  { value: "congo_brazzaville", name: "Congo (Congo-Brazzaville)" },
  { value: "costa_rica", name: "Costa Rica" },
  { value: "croatia", name: "Croatia" },
  { value: "cuba", name: "Cuba" },
  { value: "cyprus", name: "Cyprus" },
  { value: "czechia", name: "Czechia (Czech Republic)" },
  { value: "dr_congo", name: "Democratic Republic of the Congo" },
  { value: "denmark", name: "Denmark" },
  { value: "djibouti", name: "Djibouti" },
  { value: "dominica", name: "Dominica" },
  { value: "dominican_republic", name: "Dominican Republic" },
  { value: "ecuador", name: "Ecuador" },
  { value: "egypt", name: "Egypt" },
  { value: "el_salvador", name: "El Salvador" },
  { value: "equatorial_guinea", name: "Equatorial Guinea" },
  { value: "eritrea", name: "Eritrea" },
  { value: "estonia", name: "Estonia" },
  { value: "eswatini", name: "Eswatini (formerly Swaziland)" },
  { value: "ethiopia", name: "Ethiopia" },
  { value: "fiji", name: "Fiji" },
  { value: "finland", name: "Finland" },
  { value: "france", name: "France" },
  { value: "gabon", name: "Gabon" },
  { value: "gambia", name: "Gambia" },
  { value: "georgia", name: "Georgia" },
  { value: "germany", name: "Germany" },
  { value: "ghana", name: "Ghana" },
  { value: "greece", name: "Greece" },
  { value: "grenada", name: "Grenada" },
  { value: "guatemala", name: "Guatemala" },
  { value: "guinea", name: "Guinea" },
  { value: "guinea_bissau", name: "Guinea-Bissau" },
  { value: "guyana", name: "Guyana" },
  { value: "haiti", name: "Haiti" },
  { value: "vatican_city", name: "Holy See" },
  { value: "honduras", name: "Honduras" },
  { value: "hungary", name: "Hungary" },
  { value: "iceland", name: "Iceland" },
  { value: "india", name: "India" },
  { value: "indonesia", name: "Indonesia" },
  { value: "iran", name: "Iran" },
  { value: "iraq", name: "Iraq" },
  { value: "ireland", name: "Ireland" },
  { value: "israel", name: "Israel" },
  { value: "italy", name: "Italy" },
  { value: "jamaica", name: "Jamaica" },
  { value: "japan", name: "Japan" },
  { value: "jordan", name: "Jordan" },
  { value: "kazakhstan", name: "Kazakhstan" },
  { value: "kenya", name: "Kenya" },
  { value: "kiribati", name: "Kiribati" },
  { value: "kuwait", name: "Kuwait" },
  { value: "kyrgyzstan", name: "Kyrgyzstan" },
  { value: "laos", name: "Laos" },
  { value: "latvia", name: "Latvia" },
  { value: "lebanon", name: "Lebanon" },
  { value: "lesotho", name: "Lesotho" },
  { value: "liberia", name: "Liberia" },
  { value: "libya", name: "Libya" },
  { value: "liechtenstein", name: "Liechtenstein" },
  { value: "lithuania", name: "Lithuania" },
  { value: "luxembourg", name: "Luxembourg" },
  { value: "madagascar", name: "Madagascar" },
  { value: "malawi", name: "Malawi" },
  { value: "malaysia", name: "Malaysia" },
  { value: "maldives", name: "Maldives" },
  { value: "mali", name: "Mali" },
  { value: "malta", name: "Malta" },
  { value: "marshall_islands", name: "Marshall Islands" },
  { value: "mauritania", name: "Mauritania" },
  { value: "mauritius", name: "Mauritius" },
  { value: "mexico", name: "Mexico" },
  { value: "micronesia", name: "Micronesia" },
  { value: "moldova", name: "Moldova" },
  { value: "monaco", name: "Monaco" },
  { value: "mongolia", name: "Mongolia" },
  { value: "montenegro", name: "Montenegro" },
  { value: "morocco", name: "Morocco" },
  { value: "mozambique", name: "Mozambique" },
  { value: "myanmar", name: "Myanmar (formerly Burma)" },
  { value: "namibia", name: "Namibia" },
  { value: "nauru", name: "Nauru" },
  { value: "nepal", name: "Nepal" },
  { value: "netherlands", name: "Netherlands" },
  { value: "new_zealand", name: "New Zealand" },
  { value: "nicaragua", name: "Nicaragua" },
  { value: "niger", name: "Niger" },
  { value: "nigeria", name: "Nigeria" },
  { value: "north_korea", name: "North Korea" },
  { value: "north_macedonia", name: "North Macedonia" },
  { value: "norway", name: "Norway" },
  { value: "oman", name: "Oman" },
  { value: "pakistan", name: "Pakistan" },
  { value: "palau", name: "Palau" },
  { value: "palestine", name: "Palestine State" },
  { value: "panama", name: "Panama" },
  { value: "papua_new_guinea", name: "Papua New Guinea" },
  { value: "paraguay", name: "Paraguay" },
  { value: "peru", name: "Peru" },
  { value: "philippines", name: "Philippines" },
  { value: "poland", name: "Poland" },
  { value: "portugal", name: "Portugal" },
  { value: "qatar", name: "Qatar" },
  { value: "romania", name: "Romania" },
  { value: "russia", name: "Russia" },
  { value: "rwanda", name: "Rwanda" },
  { value: "saint_kitts_and_nevis", name: "Saint Kitts and Nevis" },
  { value: "saint_lucia", name: "Saint Lucia" },
  { value: "saint_vincent", name: "Saint Vincent and the Grenadines" },
  { value: "samoa", name: "Samoa" },
  { value: "san_marino", name: "San Marino" },
  { value: "sao_tome_and_principe", name: "Sao Tome and Principe" },
  { value: "saudi_arabia", name: "Saudi Arabia" },
  { value: "senegal", name: "Senegal" },
  { value: "serbia", name: "Serbia" },
  { value: "seychelles", name: "Seychelles" },
  { value: "sierra_leone", name: "Sierra Leone" },
  { value: "singapore", name: "Singapore" },
  { value: "slovakia", name: "Slovakia" },
  { value: "slovenia", name: "Slovenia" },
  { value: "solomon_islands", name: "Solomon Islands" },
  { value: "somalia", name: "Somalia" },
  { value: "south_africa", name: "South Africa" },
  { value: "south_korea", name: "South Korea" },
  { value: "south_sudan", name: "South Sudan" },
  { value: "spain", name: "Spain" },
  { value: "sri_lanka", name: "Sri Lanka" },
  { value: "sudan", name: "Sudan" },
  { value: "suriname", name: "Suriname" },
  { value: "sweden", name: "Sweden" },
  { value: "switzerland", name: "Switzerland" },
  { value: "syria", name: "Syria" },
  { value: "tajikistan", name: "Tajikistan" },
  { value: "tanzania", name: "Tanzania" },
  { value: "thailand", name: "Thailand" },
  { value: "timor_leste", name: "Timor-Leste" },
  { value: "togo", name: "Togo" },
  { value: "tonga", name: "Tonga" },
  { value: "trinidad_and_tobago", name: "Trinidad and Tobago" },
  { value: "tunisia", name: "Tunisia" },
  { value: "turkey", name: "Turkey" },
  { value: "turkmenistan", name: "Turkmenistan" },
  { value: "tuvalu", name: "Tuvalu" },
  { value: "uganda", name: "Uganda" },
  { value: "ukraine", name: "Ukraine" },
  { value: "uae", name: "United Arab Emirates" },
  { value: "uk", name: "United Kingdom" },
  { value: "usa", name: "United States of America" },
  { value: "uruguay", name: "Uruguay" },
  { value: "uzbekistan", name: "Uzbekistan" },
  { value: "vanuatu", name: "Vanuatu" },
  { value: "venezuela", name: "Venezuela" },
  { value: "vietnam", name: "Vietnam" },
  { value: "yemen", name: "Yemen" },
  { value: "zambia", name: "Zambia" },
  { value: "zimbabwe", name: "Zimbabwe" },
];
